/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as OverlaysRouteImport } from './routes/overlays'
import { Route as ChatInteractionsRouteImport } from './routes/chat-interactions'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as with_navbarRouteRouteImport } from './routes/(with_navbar)/route'
import { Route as with_navbarIndexRouteImport } from './routes/(with_navbar)/index'
import { Route as OverlaysViewRouteImport } from './routes/overlays.view'
import { Route as with_navbarModerationRouteImport } from './routes/(with_navbar)/moderation'
import { Route as with_navbarLoginRouteImport } from './routes/(with_navbar)/login'
import { Route as with_navbarHomeRouteImport } from './routes/(with_navbar)/home'
import { Route as with_navbarDashboardRouteImport } from './routes/(with_navbar)/dashboard'
import { Route as with_navbarChatInteractionsRouteImport } from './routes/(with_navbar)/chat-interactions'
import { Route as with_navbarAssetsRouteImport } from './routes/(with_navbar)/assets'
import { Route as with_navbarAccountRouteImport } from './routes/(with_navbar)/account'
import { Route as with_navbarChatInteractionsIndexRouteImport } from './routes/(with_navbar)/chat-interactions/index'
import { Route as with_navbarAssetsIndexRouteImport } from './routes/(with_navbar)/assets/index'
import { Route as OverlaysViewElementIdRouteImport } from './routes/overlays.view.$elementId'
import { Route as with_navbarChatInteractionsCommandsRouteImport } from './routes/(with_navbar)/chat-interactions/commands'
import { Route as with_navbarAssetsSubBadgesRouteImport } from './routes/(with_navbar)/assets/sub-badges'
import { Route as with_navbarAssetsEmotesRouteImport } from './routes/(with_navbar)/assets/emotes'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysRoute = OverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatInteractionsRoute = ChatInteractionsRouteImport.update({
  id: '/chat-interactions',
  path: '/chat-interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const with_navbarRouteRoute = with_navbarRouteRouteImport.update({
  id: '/(with_navbar)',
  getParentRoute: () => rootRouteImport,
} as any)
const with_navbarIndexRoute = with_navbarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const OverlaysViewRoute = OverlaysViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => OverlaysRoute,
} as any)
const with_navbarModerationRoute = with_navbarModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarLoginRoute = with_navbarLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarHomeRoute = with_navbarHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarDashboardRoute = with_navbarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarChatInteractionsRoute =
  with_navbarChatInteractionsRouteImport.update({
    id: '/chat-interactions',
    path: '/chat-interactions',
    getParentRoute: () => with_navbarRouteRoute,
  } as any)
const with_navbarAssetsRoute = with_navbarAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarAccountRoute = with_navbarAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarChatInteractionsIndexRoute =
  with_navbarChatInteractionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => with_navbarChatInteractionsRoute,
  } as any)
const with_navbarAssetsIndexRoute = with_navbarAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => with_navbarAssetsRoute,
} as any)
const OverlaysViewElementIdRoute = OverlaysViewElementIdRouteImport.update({
  id: '/$elementId',
  path: '/$elementId',
  getParentRoute: () => OverlaysViewRoute,
} as any)
const with_navbarChatInteractionsCommandsRoute =
  with_navbarChatInteractionsCommandsRouteImport.update({
    id: '/commands',
    path: '/commands',
    getParentRoute: () => with_navbarChatInteractionsRoute,
  } as any)
const with_navbarAssetsSubBadgesRoute =
  with_navbarAssetsSubBadgesRouteImport.update({
    id: '/sub-badges',
    path: '/sub-badges',
    getParentRoute: () => with_navbarAssetsRoute,
  } as any)
const with_navbarAssetsEmotesRoute = with_navbarAssetsEmotesRouteImport.update({
  id: '/emotes',
  path: '/emotes',
  getParentRoute: () => with_navbarAssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/assets': typeof with_navbarAssetsRouteWithChildren
  '/chat-interactions': typeof with_navbarChatInteractionsRouteWithChildren
  '/overlays': typeof OverlaysRouteWithChildren
  '/preview': typeof PreviewRoute
  '/account': typeof with_navbarAccountRoute
  '/dashboard': typeof with_navbarDashboardRoute
  '/home': typeof with_navbarHomeRoute
  '/login': typeof with_navbarLoginRoute
  '/moderation': typeof with_navbarModerationRoute
  '/overlays/view': typeof OverlaysViewRouteWithChildren
  '/': typeof with_navbarIndexRoute
  '/assets/emotes': typeof with_navbarAssetsEmotesRoute
  '/assets/sub-badges': typeof with_navbarAssetsSubBadgesRoute
  '/chat-interactions/commands': typeof with_navbarChatInteractionsCommandsRoute
  '/overlays/view/$elementId': typeof OverlaysViewElementIdRoute
  '/assets/': typeof with_navbarAssetsIndexRoute
  '/chat-interactions/': typeof with_navbarChatInteractionsIndexRoute
}
export interface FileRoutesByTo {
  '/assets': typeof with_navbarAssetsIndexRoute
  '/chat-interactions': typeof with_navbarChatInteractionsIndexRoute
  '/overlays': typeof OverlaysRouteWithChildren
  '/preview': typeof PreviewRoute
  '/account': typeof with_navbarAccountRoute
  '/dashboard': typeof with_navbarDashboardRoute
  '/home': typeof with_navbarHomeRoute
  '/login': typeof with_navbarLoginRoute
  '/moderation': typeof with_navbarModerationRoute
  '/overlays/view': typeof OverlaysViewRouteWithChildren
  '/': typeof with_navbarIndexRoute
  '/assets/emotes': typeof with_navbarAssetsEmotesRoute
  '/assets/sub-badges': typeof with_navbarAssetsSubBadgesRoute
  '/chat-interactions/commands': typeof with_navbarChatInteractionsCommandsRoute
  '/overlays/view/$elementId': typeof OverlaysViewElementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(with_navbar)': typeof with_navbarRouteRouteWithChildren
  '/assets': typeof AssetsRoute
  '/chat-interactions': typeof ChatInteractionsRoute
  '/overlays': typeof OverlaysRouteWithChildren
  '/preview': typeof PreviewRoute
  '/(with_navbar)/account': typeof with_navbarAccountRoute
  '/(with_navbar)/assets': typeof with_navbarAssetsRouteWithChildren
  '/(with_navbar)/chat-interactions': typeof with_navbarChatInteractionsRouteWithChildren
  '/(with_navbar)/dashboard': typeof with_navbarDashboardRoute
  '/(with_navbar)/home': typeof with_navbarHomeRoute
  '/(with_navbar)/login': typeof with_navbarLoginRoute
  '/(with_navbar)/moderation': typeof with_navbarModerationRoute
  '/overlays/view': typeof OverlaysViewRouteWithChildren
  '/(with_navbar)/': typeof with_navbarIndexRoute
  '/(with_navbar)/assets/emotes': typeof with_navbarAssetsEmotesRoute
  '/(with_navbar)/assets/sub-badges': typeof with_navbarAssetsSubBadgesRoute
  '/(with_navbar)/chat-interactions/commands': typeof with_navbarChatInteractionsCommandsRoute
  '/overlays/view/$elementId': typeof OverlaysViewElementIdRoute
  '/(with_navbar)/assets/': typeof with_navbarAssetsIndexRoute
  '/(with_navbar)/chat-interactions/': typeof with_navbarChatInteractionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/assets'
    | '/chat-interactions'
    | '/overlays'
    | '/preview'
    | '/account'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/moderation'
    | '/overlays/view'
    | '/'
    | '/assets/emotes'
    | '/assets/sub-badges'
    | '/chat-interactions/commands'
    | '/overlays/view/$elementId'
    | '/assets/'
    | '/chat-interactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assets'
    | '/chat-interactions'
    | '/overlays'
    | '/preview'
    | '/account'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/moderation'
    | '/overlays/view'
    | '/'
    | '/assets/emotes'
    | '/assets/sub-badges'
    | '/chat-interactions/commands'
    | '/overlays/view/$elementId'
  id:
    | '__root__'
    | '/(with_navbar)'
    | '/assets'
    | '/chat-interactions'
    | '/overlays'
    | '/preview'
    | '/(with_navbar)/account'
    | '/(with_navbar)/assets'
    | '/(with_navbar)/chat-interactions'
    | '/(with_navbar)/dashboard'
    | '/(with_navbar)/home'
    | '/(with_navbar)/login'
    | '/(with_navbar)/moderation'
    | '/overlays/view'
    | '/(with_navbar)/'
    | '/(with_navbar)/assets/emotes'
    | '/(with_navbar)/assets/sub-badges'
    | '/(with_navbar)/chat-interactions/commands'
    | '/overlays/view/$elementId'
    | '/(with_navbar)/assets/'
    | '/(with_navbar)/chat-interactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  with_navbarRouteRoute: typeof with_navbarRouteRouteWithChildren
  AssetsRoute: typeof AssetsRoute
  ChatInteractionsRoute: typeof ChatInteractionsRoute
  OverlaysRoute: typeof OverlaysRouteWithChildren
  PreviewRoute: typeof PreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays': {
      id: '/overlays'
      path: '/overlays'
      fullPath: '/overlays'
      preLoaderRoute: typeof OverlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-interactions': {
      id: '/chat-interactions'
      path: '/chat-interactions'
      fullPath: '/chat-interactions'
      preLoaderRoute: typeof ChatInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with_navbar)': {
      id: '/(with_navbar)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof with_navbarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with_navbar)/': {
      id: '/(with_navbar)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof with_navbarIndexRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/overlays/view': {
      id: '/overlays/view'
      path: '/view'
      fullPath: '/overlays/view'
      preLoaderRoute: typeof OverlaysViewRouteImport
      parentRoute: typeof OverlaysRoute
    }
    '/(with_navbar)/moderation': {
      id: '/(with_navbar)/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof with_navbarModerationRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/login': {
      id: '/(with_navbar)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof with_navbarLoginRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/home': {
      id: '/(with_navbar)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof with_navbarHomeRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/dashboard': {
      id: '/(with_navbar)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof with_navbarDashboardRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/chat-interactions': {
      id: '/(with_navbar)/chat-interactions'
      path: '/chat-interactions'
      fullPath: '/chat-interactions'
      preLoaderRoute: typeof with_navbarChatInteractionsRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/assets': {
      id: '/(with_navbar)/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof with_navbarAssetsRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/account': {
      id: '/(with_navbar)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof with_navbarAccountRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/chat-interactions/': {
      id: '/(with_navbar)/chat-interactions/'
      path: '/'
      fullPath: '/chat-interactions/'
      preLoaderRoute: typeof with_navbarChatInteractionsIndexRouteImport
      parentRoute: typeof with_navbarChatInteractionsRoute
    }
    '/(with_navbar)/assets/': {
      id: '/(with_navbar)/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof with_navbarAssetsIndexRouteImport
      parentRoute: typeof with_navbarAssetsRoute
    }
    '/overlays/view/$elementId': {
      id: '/overlays/view/$elementId'
      path: '/$elementId'
      fullPath: '/overlays/view/$elementId'
      preLoaderRoute: typeof OverlaysViewElementIdRouteImport
      parentRoute: typeof OverlaysViewRoute
    }
    '/(with_navbar)/chat-interactions/commands': {
      id: '/(with_navbar)/chat-interactions/commands'
      path: '/commands'
      fullPath: '/chat-interactions/commands'
      preLoaderRoute: typeof with_navbarChatInteractionsCommandsRouteImport
      parentRoute: typeof with_navbarChatInteractionsRoute
    }
    '/(with_navbar)/assets/sub-badges': {
      id: '/(with_navbar)/assets/sub-badges'
      path: '/sub-badges'
      fullPath: '/assets/sub-badges'
      preLoaderRoute: typeof with_navbarAssetsSubBadgesRouteImport
      parentRoute: typeof with_navbarAssetsRoute
    }
    '/(with_navbar)/assets/emotes': {
      id: '/(with_navbar)/assets/emotes'
      path: '/emotes'
      fullPath: '/assets/emotes'
      preLoaderRoute: typeof with_navbarAssetsEmotesRouteImport
      parentRoute: typeof with_navbarAssetsRoute
    }
  }
}

interface with_navbarAssetsRouteChildren {
  with_navbarAssetsEmotesRoute: typeof with_navbarAssetsEmotesRoute
  with_navbarAssetsSubBadgesRoute: typeof with_navbarAssetsSubBadgesRoute
  with_navbarAssetsIndexRoute: typeof with_navbarAssetsIndexRoute
}

const with_navbarAssetsRouteChildren: with_navbarAssetsRouteChildren = {
  with_navbarAssetsEmotesRoute: with_navbarAssetsEmotesRoute,
  with_navbarAssetsSubBadgesRoute: with_navbarAssetsSubBadgesRoute,
  with_navbarAssetsIndexRoute: with_navbarAssetsIndexRoute,
}

const with_navbarAssetsRouteWithChildren =
  with_navbarAssetsRoute._addFileChildren(with_navbarAssetsRouteChildren)

interface with_navbarChatInteractionsRouteChildren {
  with_navbarChatInteractionsCommandsRoute: typeof with_navbarChatInteractionsCommandsRoute
  with_navbarChatInteractionsIndexRoute: typeof with_navbarChatInteractionsIndexRoute
}

const with_navbarChatInteractionsRouteChildren: with_navbarChatInteractionsRouteChildren =
  {
    with_navbarChatInteractionsCommandsRoute:
      with_navbarChatInteractionsCommandsRoute,
    with_navbarChatInteractionsIndexRoute:
      with_navbarChatInteractionsIndexRoute,
  }

const with_navbarChatInteractionsRouteWithChildren =
  with_navbarChatInteractionsRoute._addFileChildren(
    with_navbarChatInteractionsRouteChildren,
  )

interface with_navbarRouteRouteChildren {
  with_navbarAccountRoute: typeof with_navbarAccountRoute
  with_navbarAssetsRoute: typeof with_navbarAssetsRouteWithChildren
  with_navbarChatInteractionsRoute: typeof with_navbarChatInteractionsRouteWithChildren
  with_navbarDashboardRoute: typeof with_navbarDashboardRoute
  with_navbarHomeRoute: typeof with_navbarHomeRoute
  with_navbarLoginRoute: typeof with_navbarLoginRoute
  with_navbarModerationRoute: typeof with_navbarModerationRoute
  with_navbarIndexRoute: typeof with_navbarIndexRoute
}

const with_navbarRouteRouteChildren: with_navbarRouteRouteChildren = {
  with_navbarAccountRoute: with_navbarAccountRoute,
  with_navbarAssetsRoute: with_navbarAssetsRouteWithChildren,
  with_navbarChatInteractionsRoute:
    with_navbarChatInteractionsRouteWithChildren,
  with_navbarDashboardRoute: with_navbarDashboardRoute,
  with_navbarHomeRoute: with_navbarHomeRoute,
  with_navbarLoginRoute: with_navbarLoginRoute,
  with_navbarModerationRoute: with_navbarModerationRoute,
  with_navbarIndexRoute: with_navbarIndexRoute,
}

const with_navbarRouteRouteWithChildren =
  with_navbarRouteRoute._addFileChildren(with_navbarRouteRouteChildren)

interface OverlaysViewRouteChildren {
  OverlaysViewElementIdRoute: typeof OverlaysViewElementIdRoute
}

const OverlaysViewRouteChildren: OverlaysViewRouteChildren = {
  OverlaysViewElementIdRoute: OverlaysViewElementIdRoute,
}

const OverlaysViewRouteWithChildren = OverlaysViewRoute._addFileChildren(
  OverlaysViewRouteChildren,
)

interface OverlaysRouteChildren {
  OverlaysViewRoute: typeof OverlaysViewRouteWithChildren
}

const OverlaysRouteChildren: OverlaysRouteChildren = {
  OverlaysViewRoute: OverlaysViewRouteWithChildren,
}

const OverlaysRouteWithChildren = OverlaysRoute._addFileChildren(
  OverlaysRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  with_navbarRouteRoute: with_navbarRouteRouteWithChildren,
  AssetsRoute: AssetsRoute,
  ChatInteractionsRoute: ChatInteractionsRoute,
  OverlaysRoute: OverlaysRouteWithChildren,
  PreviewRoute: PreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
