/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as with_navbarRouteRouteImport } from './routes/(with_navbar)/route'
import { Route as with_navbarIndexRouteImport } from './routes/(with_navbar)/index'
import { Route as WallEmoteIdRouteImport } from './routes/wall-emote.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as AdIdRouteImport } from './routes/ad.$id'
import { Route as with_navbarOverlaysRouteImport } from './routes/(with_navbar)/overlays'
import { Route as with_navbarModerationRouteImport } from './routes/(with_navbar)/moderation'
import { Route as with_navbarLoginRouteImport } from './routes/(with_navbar)/login'
import { Route as with_navbarHomeRouteImport } from './routes/(with_navbar)/home'
import { Route as with_navbarDashboardRouteImport } from './routes/(with_navbar)/dashboard'
import { Route as with_navbarChatInteractionsRouteImport } from './routes/(with_navbar)/chat-interactions'
import { Route as with_navbarAssetsRouteImport } from './routes/(with_navbar)/assets'
import { Route as with_navbarAccountRouteImport } from './routes/(with_navbar)/account'
import { Route as with_navbarOverlaysIndexRouteImport } from './routes/(with_navbar)/overlays/index'
import { Route as with_navbarChatInteractionsIndexRouteImport } from './routes/(with_navbar)/chat-interactions/index'
import { Route as with_navbarAssetsIndexRouteImport } from './routes/(with_navbar)/assets/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as with_navbarChatInteractionsCommandsRouteImport } from './routes/(with_navbar)/chat-interactions/commands'
import { Route as with_navbarAssetsSubBadgesRouteImport } from './routes/(with_navbar)/assets/sub-badges'
import { Route as with_navbarAssetsEmotesRouteImport } from './routes/(with_navbar)/assets/emotes'
import { Route as with_navbarOverlaysWallEmoteIndexRouteImport } from './routes/(with_navbar)/overlays/wall-emote/index'
import { Route as with_navbarOverlaysChatIndexRouteImport } from './routes/(with_navbar)/overlays/chat/index'
import { Route as with_navbarOverlaysAdIndexRouteImport } from './routes/(with_navbar)/overlays/ad/index'
import { Route as with_navbarOverlaysWallEmoteIdRouteImport } from './routes/(with_navbar)/overlays/wall-emote/$id'
import { Route as with_navbarOverlaysChatIdRouteImport } from './routes/(with_navbar)/overlays/chat/$id'
import { Route as with_navbarOverlaysAdIdRouteImport } from './routes/(with_navbar)/overlays/ad/$id'

const with_navbarRouteRoute = with_navbarRouteRouteImport.update({
  id: '/(with_navbar)',
  getParentRoute: () => rootRouteImport,
} as any)
const with_navbarIndexRoute = with_navbarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const WallEmoteIdRoute = WallEmoteIdRouteImport.update({
  id: '/wall-emote/$id',
  path: '/wall-emote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdIdRoute = AdIdRouteImport.update({
  id: '/ad/$id',
  path: '/ad/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const with_navbarOverlaysRoute = with_navbarOverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarModerationRoute = with_navbarModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarLoginRoute = with_navbarLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarHomeRoute = with_navbarHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarDashboardRoute = with_navbarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarChatInteractionsRoute =
  with_navbarChatInteractionsRouteImport.update({
    id: '/chat-interactions',
    path: '/chat-interactions',
    getParentRoute: () => with_navbarRouteRoute,
  } as any)
const with_navbarAssetsRoute = with_navbarAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarAccountRoute = with_navbarAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => with_navbarRouteRoute,
} as any)
const with_navbarOverlaysIndexRoute =
  with_navbarOverlaysIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => with_navbarOverlaysRoute,
  } as any)
const with_navbarChatInteractionsIndexRoute =
  with_navbarChatInteractionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => with_navbarChatInteractionsRoute,
  } as any)
const with_navbarAssetsIndexRoute = with_navbarAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => with_navbarAssetsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const with_navbarChatInteractionsCommandsRoute =
  with_navbarChatInteractionsCommandsRouteImport.update({
    id: '/commands',
    path: '/commands',
    getParentRoute: () => with_navbarChatInteractionsRoute,
  } as any)
const with_navbarAssetsSubBadgesRoute =
  with_navbarAssetsSubBadgesRouteImport.update({
    id: '/sub-badges',
    path: '/sub-badges',
    getParentRoute: () => with_navbarAssetsRoute,
  } as any)
const with_navbarAssetsEmotesRoute = with_navbarAssetsEmotesRouteImport.update({
  id: '/emotes',
  path: '/emotes',
  getParentRoute: () => with_navbarAssetsRoute,
} as any)
const with_navbarOverlaysWallEmoteIndexRoute =
  with_navbarOverlaysWallEmoteIndexRouteImport.update({
    id: '/wall-emote/',
    path: '/wall-emote/',
    getParentRoute: () => with_navbarOverlaysRoute,
  } as any)
const with_navbarOverlaysChatIndexRoute =
  with_navbarOverlaysChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => with_navbarOverlaysRoute,
  } as any)
const with_navbarOverlaysAdIndexRoute =
  with_navbarOverlaysAdIndexRouteImport.update({
    id: '/ad/',
    path: '/ad/',
    getParentRoute: () => with_navbarOverlaysRoute,
  } as any)
const with_navbarOverlaysWallEmoteIdRoute =
  with_navbarOverlaysWallEmoteIdRouteImport.update({
    id: '/wall-emote/$id',
    path: '/wall-emote/$id',
    getParentRoute: () => with_navbarOverlaysRoute,
  } as any)
const with_navbarOverlaysChatIdRoute =
  with_navbarOverlaysChatIdRouteImport.update({
    id: '/chat/$id',
    path: '/chat/$id',
    getParentRoute: () => with_navbarOverlaysRoute,
  } as any)
const with_navbarOverlaysAdIdRoute = with_navbarOverlaysAdIdRouteImport.update({
  id: '/ad/$id',
  path: '/ad/$id',
  getParentRoute: () => with_navbarOverlaysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/account': typeof with_navbarAccountRoute
  '/assets': typeof with_navbarAssetsRouteWithChildren
  '/chat-interactions': typeof with_navbarChatInteractionsRouteWithChildren
  '/dashboard': typeof with_navbarDashboardRoute
  '/home': typeof with_navbarHomeRoute
  '/login': typeof with_navbarLoginRoute
  '/moderation': typeof with_navbarModerationRoute
  '/overlays': typeof with_navbarOverlaysRouteWithChildren
  '/ad/$id': typeof AdIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/wall-emote/$id': typeof WallEmoteIdRoute
  '/': typeof with_navbarIndexRoute
  '/assets/emotes': typeof with_navbarAssetsEmotesRoute
  '/assets/sub-badges': typeof with_navbarAssetsSubBadgesRoute
  '/chat-interactions/commands': typeof with_navbarChatInteractionsCommandsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/assets/': typeof with_navbarAssetsIndexRoute
  '/chat-interactions/': typeof with_navbarChatInteractionsIndexRoute
  '/overlays/': typeof with_navbarOverlaysIndexRoute
  '/overlays/ad/$id': typeof with_navbarOverlaysAdIdRoute
  '/overlays/chat/$id': typeof with_navbarOverlaysChatIdRoute
  '/overlays/wall-emote/$id': typeof with_navbarOverlaysWallEmoteIdRoute
  '/overlays/ad': typeof with_navbarOverlaysAdIndexRoute
  '/overlays/chat': typeof with_navbarOverlaysChatIndexRoute
  '/overlays/wall-emote': typeof with_navbarOverlaysWallEmoteIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof with_navbarAccountRoute
  '/dashboard': typeof with_navbarDashboardRoute
  '/home': typeof with_navbarHomeRoute
  '/login': typeof with_navbarLoginRoute
  '/moderation': typeof with_navbarModerationRoute
  '/ad/$id': typeof AdIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/wall-emote/$id': typeof WallEmoteIdRoute
  '/': typeof with_navbarIndexRoute
  '/assets/emotes': typeof with_navbarAssetsEmotesRoute
  '/assets/sub-badges': typeof with_navbarAssetsSubBadgesRoute
  '/chat-interactions/commands': typeof with_navbarChatInteractionsCommandsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/assets': typeof with_navbarAssetsIndexRoute
  '/chat-interactions': typeof with_navbarChatInteractionsIndexRoute
  '/overlays': typeof with_navbarOverlaysIndexRoute
  '/overlays/ad/$id': typeof with_navbarOverlaysAdIdRoute
  '/overlays/chat/$id': typeof with_navbarOverlaysChatIdRoute
  '/overlays/wall-emote/$id': typeof with_navbarOverlaysWallEmoteIdRoute
  '/overlays/ad': typeof with_navbarOverlaysAdIndexRoute
  '/overlays/chat': typeof with_navbarOverlaysChatIndexRoute
  '/overlays/wall-emote': typeof with_navbarOverlaysWallEmoteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(with_navbar)': typeof with_navbarRouteRouteWithChildren
  '/(with_navbar)/account': typeof with_navbarAccountRoute
  '/(with_navbar)/assets': typeof with_navbarAssetsRouteWithChildren
  '/(with_navbar)/chat-interactions': typeof with_navbarChatInteractionsRouteWithChildren
  '/(with_navbar)/dashboard': typeof with_navbarDashboardRoute
  '/(with_navbar)/home': typeof with_navbarHomeRoute
  '/(with_navbar)/login': typeof with_navbarLoginRoute
  '/(with_navbar)/moderation': typeof with_navbarModerationRoute
  '/(with_navbar)/overlays': typeof with_navbarOverlaysRouteWithChildren
  '/ad/$id': typeof AdIdRoute
  '/chat/$id': typeof ChatIdRoute
  '/wall-emote/$id': typeof WallEmoteIdRoute
  '/(with_navbar)/': typeof with_navbarIndexRoute
  '/(with_navbar)/assets/emotes': typeof with_navbarAssetsEmotesRoute
  '/(with_navbar)/assets/sub-badges': typeof with_navbarAssetsSubBadgesRoute
  '/(with_navbar)/chat-interactions/commands': typeof with_navbarChatInteractionsCommandsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(with_navbar)/assets/': typeof with_navbarAssetsIndexRoute
  '/(with_navbar)/chat-interactions/': typeof with_navbarChatInteractionsIndexRoute
  '/(with_navbar)/overlays/': typeof with_navbarOverlaysIndexRoute
  '/(with_navbar)/overlays/ad/$id': typeof with_navbarOverlaysAdIdRoute
  '/(with_navbar)/overlays/chat/$id': typeof with_navbarOverlaysChatIdRoute
  '/(with_navbar)/overlays/wall-emote/$id': typeof with_navbarOverlaysWallEmoteIdRoute
  '/(with_navbar)/overlays/ad/': typeof with_navbarOverlaysAdIndexRoute
  '/(with_navbar)/overlays/chat/': typeof with_navbarOverlaysChatIndexRoute
  '/(with_navbar)/overlays/wall-emote/': typeof with_navbarOverlaysWallEmoteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account'
    | '/assets'
    | '/chat-interactions'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/moderation'
    | '/overlays'
    | '/ad/$id'
    | '/chat/$id'
    | '/wall-emote/$id'
    | '/'
    | '/assets/emotes'
    | '/assets/sub-badges'
    | '/chat-interactions/commands'
    | '/api/auth/$'
    | '/assets/'
    | '/chat-interactions/'
    | '/overlays/'
    | '/overlays/ad/$id'
    | '/overlays/chat/$id'
    | '/overlays/wall-emote/$id'
    | '/overlays/ad'
    | '/overlays/chat'
    | '/overlays/wall-emote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/moderation'
    | '/ad/$id'
    | '/chat/$id'
    | '/wall-emote/$id'
    | '/'
    | '/assets/emotes'
    | '/assets/sub-badges'
    | '/chat-interactions/commands'
    | '/api/auth/$'
    | '/assets'
    | '/chat-interactions'
    | '/overlays'
    | '/overlays/ad/$id'
    | '/overlays/chat/$id'
    | '/overlays/wall-emote/$id'
    | '/overlays/ad'
    | '/overlays/chat'
    | '/overlays/wall-emote'
  id:
    | '__root__'
    | '/(with_navbar)'
    | '/(with_navbar)/account'
    | '/(with_navbar)/assets'
    | '/(with_navbar)/chat-interactions'
    | '/(with_navbar)/dashboard'
    | '/(with_navbar)/home'
    | '/(with_navbar)/login'
    | '/(with_navbar)/moderation'
    | '/(with_navbar)/overlays'
    | '/ad/$id'
    | '/chat/$id'
    | '/wall-emote/$id'
    | '/(with_navbar)/'
    | '/(with_navbar)/assets/emotes'
    | '/(with_navbar)/assets/sub-badges'
    | '/(with_navbar)/chat-interactions/commands'
    | '/api/auth/$'
    | '/(with_navbar)/assets/'
    | '/(with_navbar)/chat-interactions/'
    | '/(with_navbar)/overlays/'
    | '/(with_navbar)/overlays/ad/$id'
    | '/(with_navbar)/overlays/chat/$id'
    | '/(with_navbar)/overlays/wall-emote/$id'
    | '/(with_navbar)/overlays/ad/'
    | '/(with_navbar)/overlays/chat/'
    | '/(with_navbar)/overlays/wall-emote/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  with_navbarRouteRoute: typeof with_navbarRouteRouteWithChildren
  AdIdRoute: typeof AdIdRoute
  ChatIdRoute: typeof ChatIdRoute
  WallEmoteIdRoute: typeof WallEmoteIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(with_navbar)': {
      id: '/(with_navbar)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof with_navbarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with_navbar)/': {
      id: '/(with_navbar)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof with_navbarIndexRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/wall-emote/$id': {
      id: '/wall-emote/$id'
      path: '/wall-emote/$id'
      fullPath: '/wall-emote/$id'
      preLoaderRoute: typeof WallEmoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad/$id': {
      id: '/ad/$id'
      path: '/ad/$id'
      fullPath: '/ad/$id'
      preLoaderRoute: typeof AdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with_navbar)/overlays': {
      id: '/(with_navbar)/overlays'
      path: '/overlays'
      fullPath: '/overlays'
      preLoaderRoute: typeof with_navbarOverlaysRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/moderation': {
      id: '/(with_navbar)/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof with_navbarModerationRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/login': {
      id: '/(with_navbar)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof with_navbarLoginRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/home': {
      id: '/(with_navbar)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof with_navbarHomeRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/dashboard': {
      id: '/(with_navbar)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof with_navbarDashboardRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/chat-interactions': {
      id: '/(with_navbar)/chat-interactions'
      path: '/chat-interactions'
      fullPath: '/chat-interactions'
      preLoaderRoute: typeof with_navbarChatInteractionsRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/assets': {
      id: '/(with_navbar)/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof with_navbarAssetsRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/account': {
      id: '/(with_navbar)/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof with_navbarAccountRouteImport
      parentRoute: typeof with_navbarRouteRoute
    }
    '/(with_navbar)/overlays/': {
      id: '/(with_navbar)/overlays/'
      path: '/'
      fullPath: '/overlays/'
      preLoaderRoute: typeof with_navbarOverlaysIndexRouteImport
      parentRoute: typeof with_navbarOverlaysRoute
    }
    '/(with_navbar)/chat-interactions/': {
      id: '/(with_navbar)/chat-interactions/'
      path: '/'
      fullPath: '/chat-interactions/'
      preLoaderRoute: typeof with_navbarChatInteractionsIndexRouteImport
      parentRoute: typeof with_navbarChatInteractionsRoute
    }
    '/(with_navbar)/assets/': {
      id: '/(with_navbar)/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof with_navbarAssetsIndexRouteImport
      parentRoute: typeof with_navbarAssetsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(with_navbar)/chat-interactions/commands': {
      id: '/(with_navbar)/chat-interactions/commands'
      path: '/commands'
      fullPath: '/chat-interactions/commands'
      preLoaderRoute: typeof with_navbarChatInteractionsCommandsRouteImport
      parentRoute: typeof with_navbarChatInteractionsRoute
    }
    '/(with_navbar)/assets/sub-badges': {
      id: '/(with_navbar)/assets/sub-badges'
      path: '/sub-badges'
      fullPath: '/assets/sub-badges'
      preLoaderRoute: typeof with_navbarAssetsSubBadgesRouteImport
      parentRoute: typeof with_navbarAssetsRoute
    }
    '/(with_navbar)/assets/emotes': {
      id: '/(with_navbar)/assets/emotes'
      path: '/emotes'
      fullPath: '/assets/emotes'
      preLoaderRoute: typeof with_navbarAssetsEmotesRouteImport
      parentRoute: typeof with_navbarAssetsRoute
    }
    '/(with_navbar)/overlays/wall-emote/': {
      id: '/(with_navbar)/overlays/wall-emote/'
      path: '/wall-emote'
      fullPath: '/overlays/wall-emote'
      preLoaderRoute: typeof with_navbarOverlaysWallEmoteIndexRouteImport
      parentRoute: typeof with_navbarOverlaysRoute
    }
    '/(with_navbar)/overlays/chat/': {
      id: '/(with_navbar)/overlays/chat/'
      path: '/chat'
      fullPath: '/overlays/chat'
      preLoaderRoute: typeof with_navbarOverlaysChatIndexRouteImport
      parentRoute: typeof with_navbarOverlaysRoute
    }
    '/(with_navbar)/overlays/ad/': {
      id: '/(with_navbar)/overlays/ad/'
      path: '/ad'
      fullPath: '/overlays/ad'
      preLoaderRoute: typeof with_navbarOverlaysAdIndexRouteImport
      parentRoute: typeof with_navbarOverlaysRoute
    }
    '/(with_navbar)/overlays/wall-emote/$id': {
      id: '/(with_navbar)/overlays/wall-emote/$id'
      path: '/wall-emote/$id'
      fullPath: '/overlays/wall-emote/$id'
      preLoaderRoute: typeof with_navbarOverlaysWallEmoteIdRouteImport
      parentRoute: typeof with_navbarOverlaysRoute
    }
    '/(with_navbar)/overlays/chat/$id': {
      id: '/(with_navbar)/overlays/chat/$id'
      path: '/chat/$id'
      fullPath: '/overlays/chat/$id'
      preLoaderRoute: typeof with_navbarOverlaysChatIdRouteImport
      parentRoute: typeof with_navbarOverlaysRoute
    }
    '/(with_navbar)/overlays/ad/$id': {
      id: '/(with_navbar)/overlays/ad/$id'
      path: '/ad/$id'
      fullPath: '/overlays/ad/$id'
      preLoaderRoute: typeof with_navbarOverlaysAdIdRouteImport
      parentRoute: typeof with_navbarOverlaysRoute
    }
  }
}

interface with_navbarAssetsRouteChildren {
  with_navbarAssetsEmotesRoute: typeof with_navbarAssetsEmotesRoute
  with_navbarAssetsSubBadgesRoute: typeof with_navbarAssetsSubBadgesRoute
  with_navbarAssetsIndexRoute: typeof with_navbarAssetsIndexRoute
}

const with_navbarAssetsRouteChildren: with_navbarAssetsRouteChildren = {
  with_navbarAssetsEmotesRoute: with_navbarAssetsEmotesRoute,
  with_navbarAssetsSubBadgesRoute: with_navbarAssetsSubBadgesRoute,
  with_navbarAssetsIndexRoute: with_navbarAssetsIndexRoute,
}

const with_navbarAssetsRouteWithChildren =
  with_navbarAssetsRoute._addFileChildren(with_navbarAssetsRouteChildren)

interface with_navbarChatInteractionsRouteChildren {
  with_navbarChatInteractionsCommandsRoute: typeof with_navbarChatInteractionsCommandsRoute
  with_navbarChatInteractionsIndexRoute: typeof with_navbarChatInteractionsIndexRoute
}

const with_navbarChatInteractionsRouteChildren: with_navbarChatInteractionsRouteChildren =
  {
    with_navbarChatInteractionsCommandsRoute:
      with_navbarChatInteractionsCommandsRoute,
    with_navbarChatInteractionsIndexRoute:
      with_navbarChatInteractionsIndexRoute,
  }

const with_navbarChatInteractionsRouteWithChildren =
  with_navbarChatInteractionsRoute._addFileChildren(
    with_navbarChatInteractionsRouteChildren,
  )

interface with_navbarOverlaysRouteChildren {
  with_navbarOverlaysIndexRoute: typeof with_navbarOverlaysIndexRoute
  with_navbarOverlaysAdIdRoute: typeof with_navbarOverlaysAdIdRoute
  with_navbarOverlaysChatIdRoute: typeof with_navbarOverlaysChatIdRoute
  with_navbarOverlaysWallEmoteIdRoute: typeof with_navbarOverlaysWallEmoteIdRoute
  with_navbarOverlaysAdIndexRoute: typeof with_navbarOverlaysAdIndexRoute
  with_navbarOverlaysChatIndexRoute: typeof with_navbarOverlaysChatIndexRoute
  with_navbarOverlaysWallEmoteIndexRoute: typeof with_navbarOverlaysWallEmoteIndexRoute
}

const with_navbarOverlaysRouteChildren: with_navbarOverlaysRouteChildren = {
  with_navbarOverlaysIndexRoute: with_navbarOverlaysIndexRoute,
  with_navbarOverlaysAdIdRoute: with_navbarOverlaysAdIdRoute,
  with_navbarOverlaysChatIdRoute: with_navbarOverlaysChatIdRoute,
  with_navbarOverlaysWallEmoteIdRoute: with_navbarOverlaysWallEmoteIdRoute,
  with_navbarOverlaysAdIndexRoute: with_navbarOverlaysAdIndexRoute,
  with_navbarOverlaysChatIndexRoute: with_navbarOverlaysChatIndexRoute,
  with_navbarOverlaysWallEmoteIndexRoute:
    with_navbarOverlaysWallEmoteIndexRoute,
}

const with_navbarOverlaysRouteWithChildren =
  with_navbarOverlaysRoute._addFileChildren(with_navbarOverlaysRouteChildren)

interface with_navbarRouteRouteChildren {
  with_navbarAccountRoute: typeof with_navbarAccountRoute
  with_navbarAssetsRoute: typeof with_navbarAssetsRouteWithChildren
  with_navbarChatInteractionsRoute: typeof with_navbarChatInteractionsRouteWithChildren
  with_navbarDashboardRoute: typeof with_navbarDashboardRoute
  with_navbarHomeRoute: typeof with_navbarHomeRoute
  with_navbarLoginRoute: typeof with_navbarLoginRoute
  with_navbarModerationRoute: typeof with_navbarModerationRoute
  with_navbarOverlaysRoute: typeof with_navbarOverlaysRouteWithChildren
  with_navbarIndexRoute: typeof with_navbarIndexRoute
}

const with_navbarRouteRouteChildren: with_navbarRouteRouteChildren = {
  with_navbarAccountRoute: with_navbarAccountRoute,
  with_navbarAssetsRoute: with_navbarAssetsRouteWithChildren,
  with_navbarChatInteractionsRoute:
    with_navbarChatInteractionsRouteWithChildren,
  with_navbarDashboardRoute: with_navbarDashboardRoute,
  with_navbarHomeRoute: with_navbarHomeRoute,
  with_navbarLoginRoute: with_navbarLoginRoute,
  with_navbarModerationRoute: with_navbarModerationRoute,
  with_navbarOverlaysRoute: with_navbarOverlaysRouteWithChildren,
  with_navbarIndexRoute: with_navbarIndexRoute,
}

const with_navbarRouteRouteWithChildren =
  with_navbarRouteRoute._addFileChildren(with_navbarRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  with_navbarRouteRoute: with_navbarRouteRouteWithChildren,
  AdIdRoute: AdIdRoute,
  ChatIdRoute: ChatIdRoute,
  WallEmoteIdRoute: WallEmoteIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
